/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MangaIdRouteImport } from './routes/manga.$id'
import { Route as MangaIdChapterNumRouteImport } from './routes/manga.$id.chapter.$num'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIdRoute = MangaIdRouteImport.update({
  id: '/manga/$id',
  path: '/manga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIdChapterNumRoute = MangaIdChapterNumRouteImport.update({
  id: '/chapter/$num',
  path: '/chapter/$num',
  getParentRoute: () => MangaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/manga/$id': typeof MangaIdRouteWithChildren
  '/manga/$id/chapter/$num': typeof MangaIdChapterNumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/manga/$id': typeof MangaIdRouteWithChildren
  '/manga/$id/chapter/$num': typeof MangaIdChapterNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/manga/$id': typeof MangaIdRouteWithChildren
  '/manga/$id/chapter/$num': typeof MangaIdChapterNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/auth' | '/manga/$id' | '/manga/$id/chapter/$num'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/auth' | '/manga/$id' | '/manga/$id/chapter/$num'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/manga/$id'
    | '/manga/$id/chapter/$num'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  MangaIdRoute: typeof MangaIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$id': {
      id: '/manga/$id'
      path: '/manga/$id'
      fullPath: '/manga/$id'
      preLoaderRoute: typeof MangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$id/chapter/$num': {
      id: '/manga/$id/chapter/$num'
      path: '/chapter/$num'
      fullPath: '/manga/$id/chapter/$num'
      preLoaderRoute: typeof MangaIdChapterNumRouteImport
      parentRoute: typeof MangaIdRoute
    }
  }
}

interface MangaIdRouteChildren {
  MangaIdChapterNumRoute: typeof MangaIdChapterNumRoute
}

const MangaIdRouteChildren: MangaIdRouteChildren = {
  MangaIdChapterNumRoute: MangaIdChapterNumRoute,
}

const MangaIdRouteWithChildren =
  MangaIdRoute._addFileChildren(MangaIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  MangaIdRoute: MangaIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
